- Cargo.lock
- README.md
- build.sh
- kms/Cargo.toml
- kms/kms.toml
- kms/src/config.rs
- kms/src/ct_log.rs
- kms/src/main.rs
- kms/src/main_service.rs
- ra-tls/src/attestation.rs
- run.sh
- teepod/rpc/proto/teepod_rpc.proto
- teepod/src/console.html
- teepod/src/main_service.rs
- teepod/src/vm.rs
This PR adds support for upgrading App with a new docker-compose.yaml.
Steps:
- Submit the new docker-compose.yaml at teepod dashboard
- Run the shell script to add the upgrade to KMS whitelist
How it works:
When the new docker-compose.yaml is submitted, it replaces the old one in the VM instance directory.
In the later boot stage in initramfs, two app IDs are measured to RTMR and reported to KMS - the original `app_id` calculated from the docker-compose.yaml used to deploy the app, and the `upgraded_app_id` calculated from the new docker-compose.yaml.
KMS checks if the `app_id` is allowed to upgrade to `upgraded_app_id` in the whitelist. If yes, it returns the key of the original `app_id`.
After upgrade, the `app_id` of the App remains unchanged.
> Support for upgrading App

- build.sh
- tproxy/src/proxy.rs
- tproxy/src/proxy/tls_passthough.rs
- tproxy/src/proxy/tls_terminate.rs
Adds support for TLS passthrough when using shared domain. This enables end-to-end encryption from user to CVM even when using the shared domain.
Adding `s` at the end of the `<app_id>-<port>s` part in the domain enables passthrough mode.
Example, accessing the following URL will passthrough TLS traffic directly to the CVM without terminating at the proxy:
```
https://f668eb3941231702a0b3c214edeb464e98a5873f-8043s.dstack-dev.phala.network/
```
> tproxy: Support for TLS passthrough when using shared domain.

- build.sh
- ra-rpc/src/rocket_helper.rs
- teepod/rpc/proto/teepod_rpc.proto
- teepod/src/app.rs
- teepod/src/config.rs
- teepod/src/console.html
- teepod/src/main.rs
- teepod/src/main_service.rs
- teepod/src/vm.rs
- teepod/teepod.toml
After adding config in the `teepod.toml` as below:
```
[cvm.port_mapping]
enabled = true
address = "127.0.0.1"
range = [
{ protocol = "tcp", from = 1, to = 20000 },
]
```
the web UI shows up port mapping config when deploying new instances:
> teepod: Support for mapping host port to CVM

- Cargo.lock
- ra-tls/src/cert.rs
- tdx-attest/src/eventlog.rs
- tdxctl/Cargo.toml
- tdxctl/src/fde_setup.rs
- tdxctl/src/main.rs
- tdxctl/src/utils.rs
- teepod/src/console.html
This PR adds support to teepod for running CVMs without KMS. If the `kms` feature is not enabled in the app-compose.json, the CVM will operate without KMS. It generates a random disk encryption key upon each startup, causing the disk to be formatted every reboot. Data persistence across reboots is not available in this mode.
> Support for running CVM without KMS

- teepod/src/app.rs
- teepod/src/config.rs
- teepod/src/vm.rs
- teepod/teepod.toml
This is necessary for TaaS as the default slirp networking lacks network ACL feature.
> teepod: Support for custom netdev

- Cargo.lock
- Cargo.toml
- certbot/cli/Cargo.toml
- certgen/src/main.rs
- kms/rpc/Cargo.toml
- ra-rpc/Cargo.toml
- ra-rpc/src/client.rs
- tappd/rpc/Cargo.toml
- tdxctl/Cargo.toml
- tdxctl/src/fde_setup.rs
- tdxctl/src/main.rs
- tdxctl/src/tboot.rs
- teepod/rpc/Cargo.toml
- tproxy/rpc/Cargo.toml
Currently, this would cause the tproxy crash.
> tdxctl: Use Rust client instead of curl

- .github/workflows/rust.yml
- kms/rpc/build.rs
- kms/rpc/src/generated.rs
- tappd/rpc/build.rs
- tappd/rpc/src/generated.rs
- teepod/rpc/build.rs
- teepod/rpc/src/generated.rs
- tproxy/rpc/build.rs
- tproxy/rpc/src/generated.rs
It is no longer needed as we don't face substrate any more.
> Disable scale ext for protos

- Cargo.toml
- tproxy/Cargo.toml
- tproxy/src/config.rs
- tproxy/src/main.rs
- tproxy/tproxy.toml
To prevent the `Too many open files` error caused by the 1024 soft limit, tproxy automatically increases the threshold to the maximum hard limit (typically 1M).
> tproxy: Auto set ulimit -n

- tproxy/src/config.rs
- tproxy/src/proxy.rs
- tproxy/src/proxy/tls_passthough.rs
- tproxy/src/proxy/tls_terminate.rs
- tproxy/tproxy.toml
There are many connections that remains there keeping the fd usage. This PR allow tproxy to limit the life duration of a connect, default to 5 hours, so that any connection's max live time is limited.
> tproxy: Config for overall timeout for a connection

- tappd/src/http_routes.rs
- tappd/templates/dashboard.html
- teepod/src/console.html
Allows human readable `since=` and allows `tail=`. (e.g. `since=1h`, `tail=1000`).
> tappd: Better logs filter

- Cargo.lock
- Cargo.toml
- basefiles/app-compose.service
- basefiles/app-compose.sh
- guest-api/Cargo.toml
- guest-api/build.rs
- guest-api/proto/guest_api.proto
- guest-api/src/client.rs
- guest-api/src/generated/mod.rs
- guest-api/src/lib.rs
- supervisor/src/process.rs
- tappd/Cargo.toml
- tappd/rpc/proto/tappd_rpc.proto
- tappd/src/guest_api_routes.rs
- tappd/src/guest_api_service.rs
- tappd/src/http_routes.rs
- tappd/src/main.rs
- tappd/src/models.rs
- tappd/src/rpc_service.rs
- tappd/tappd.toml
- teepod/Cargo.toml
- teepod/rpc/proto/teepod_rpc.proto
- teepod/src/app.rs
- teepod/src/app/image.rs
- teepod/src/app/qemu.rs
- teepod/src/console.html
- teepod/src/guest_api_routes.rs
- teepod/src/guest_api_service.rs
- teepod/src/main.rs
- teepod/src/main_service.rs
This PR adds vsock api implementation in tappd. Currently defined APIs are:
```proto
service GuestApi {
rpc Info(google.protobuf.Empty) returns (GuestInfo);
rpc SysInfo(google.protobuf.Empty) returns (SystemInfo);
rpc NetworkInfo(google.protobuf.Empty) returns (NetworkInformation);
rpc ListContainers(google.protobuf.Empty) returns (ListContainersResponse);
rpc Shutdown(google.protobuf.Empty) returns (google.protobuf.Empty);
}
```
The APIs are also proxied by teepod for Cloud management.
This PR also includes graceful shutdown VMs.
> tappd: Implement vsock-based guest API

- basefiles/app-compose.service
- basefiles/tboot.service
- basefiles/wg-checker.service
- basefiles/wg-checker.sh
- tdxctl/src/tboot.rs
Our previously released images suffers from WireGuard connectivity issues. The root cause was identified as a bug in the QEMU built-in NAT, which occasionally incorrectly translates the WireGuard server's IP address to `10.0.2.3`, leading to incorrect endpoint field updates
To resolve this, we've implemented dual safeguards:
- Iptables-based filtering to restrict packet transmission from authorized endpoints only. (Thanks to @nanometerzhu's good idea.)
- Automated endpoint monitoring service with self-recovery. (Serving as a failsafe for the iptables rule.)
> Add workarounds for wg endpoint changes

- basefiles/app-compose.sh
So that the previous containers are removed when renamed in docker-compose.yaml
> compose: Add --remove-orphans to docker compose up

- basefiles/tboot.sh
We previously added this as a workaround for the cloud could not get the status if the vm failed to boot. Now there is API the get the boot state, this is no longer needed.
> Don't shutdown when tboot.sh fail

- kms/rpc/proto/kms_rpc.proto
- kms/src/main_service.rs
- tappd/rpc/proto/tappd_rpc.proto
- tappd/src/http_routes.rs
- tappd/src/rpc_service.rs
- teepod/rpc/proto/teepod_rpc.proto
- teepod/src/config.rs
- teepod/src/main_service.rs
- teepod/teepod.toml
- tproxy/rpc/proto/tproxy_rpc.proto
- tproxy/src/main_service.rs
- tproxy/templates/cvmlist.html
This PR have added the GetMeta API for Teepod, TProxy, and KMS. This API retrieves the configured behavior for each core service:
- **Teepod**: Returns the associated TProxy and KMS addresses along with the maximum capacity.
- **TProxy**: Currently returns statistics only, as non-critical configuration options should not be exposed.
- **KMS**: Detects whether `allow_any_upgrade` is enabled to determine if an associated CVM can process upgrades.
These APIs allow the creation of a standalone service that connects to multiple DStack deployments and activates various features based on metadata.
> GetMeta APIs

- basefiles/app-compose.service
- basefiles/app-compose.sh
- basefiles/tboot.sh
In the previous implementation, the cvm ran `docker compose up --remove-orphans -d` on startup, where the --remove-orphans flag is to remove the containers no longer defined in the compose file after an upgrade.
However, that's not enough. Although `--remove-orphans` removes the orphans, because it runs after the dockerd has started, the orphan containers would still run for a short period of time before being removed, if its RestartPolicy is always or so.
This PR solves it by temporarily disabling the dockerd from being able to start containers in a hacked way: `chmod +x /usr/bin/containerd-shim-runc-v2` before the dockerd starts. And recovering it after the docker compose has removed the orphans.
> cvm: A better way to remove orphans

- Cargo.lock
- Cargo.toml
- http-client/Cargo.toml
- http-client/src/prpc.rs
- ra-rpc/Cargo.toml
- ra-rpc/src/client.rs
For forward compatible reason. Because future third party server side would likely only implement the json codec variant.
> prpc: Choose json codec in prpc clients

- basefiles/app-compose.sh
- tdxctl/src/tboot.rs
- teepod/src/console.html
- teepod/src/main_service.rs
This PR Adds support for running a custom script before the `docker compose up`.
Example:
> cvm: Add pre_launch_script in app-compose

- key-provider-build/docker-compose.yaml
- key-provider-build/run.sh
Updates
1. Make docker always restart in docker compose file
2. Make the local provider run as daemon by add `-d` argument to docker compose up
3. Add docker log options to limit the log file size
> make docker restart always and run as daemon

- dstack-types/src/lib.rs
- tappd/src/guest_api_service.rs
- tdxctl/src/fde_setup.rs
- tdxctl/src/tboot.rs
- teepod/rpc/proto/teepod_rpc.proto
- teepod/src/app.rs
- teepod/src/config.rs
- teepod/src/main_service.rs
- teepod/teepod.toml
So that cvm can fallback to other kms/tproxy nodes if part of them are down.
> cvm: Support for multiple kms and tproxy URLs

- teepod/src/console.html
Now the env var names required to be declared in the app-compose.json to be passed in to Tapp.
This prevents hidden arbitrary env variables from being passed to TApp.
> cvm: Only allow wihtelisted envs

- supervisor/client/src/lib.rs
- teepod/src/config.rs
- teepod/src/main.rs
- teepod/teepod.toml
Now, the supervisor is not detached by default.
> teepod: Support for non-detached supervisor

- dstack-types/src/lib.rs
- kms/tapp/deploy-to-teepod.sh
- ra-tls/src/attestation.rs
- tdxctl/src/fde_setup.rs
- tdxctl/src/main.rs
- teepod/src/console.html
- teepod/src/teepod-cli.py
- tproxy/tapp/deploy-to-teepod.sh
This PR introduces an option `no_instance_id` in the app-compose.json, which removes the instance-id from RTMR3.
This PR also eliminates the `rootfs_hash` from RTMR3, as it is already measured in RTMR2.
> Deterministic RTMR3

- teepod/src/app/qemu.rs
- teepod/src/config.rs
- teepod/src/setup-user.sh
- teepod/teepod.toml
This PR adds a bash script to config the user network firewall which prevent the CVMs from accessing host `127.0.0.1`.
This is a temporary solution, as designing a new network structure over bare QEMU is not straightforward. We may transition to using LibVirt in the future.
> teepod: Add a script to configure the user network firewall

- kms/src/main.rs
- kms/src/onboard_service.rs
- tdxctl/src/fde_setup.rs
This PR Adds the mr_aggregated of KMS to RTMR3 if exists, so that the MRs of the  full trust chain are aggregated into the App CVM's MRs.
```
┌──────────────────────────── Application MRs ─────────────────────────────┐
│                                                                           │
│  MRTD                                                                     │
│  RTMR[0-2]                                                                │
│                                                                           │
│  RTMR[3] ─────┬─── App Info                                              │
│               │                                                           │
│               └──────────► ┌─────────── MR-KMS ────────────┐             │
│                            │ …
```
> cvm: Add mr-kms to RTMR3

- dstack-types/src/shared_filenames.rs
- teepod/src/app.rs
- teepod/src/app/image.rs
- teepod/src/config.rs
We introduced breaking changes in v0.4 that prevented teepod from launching v0.3.x images. This PR implements backward compatibility in teepod to support v0.3.x images.
> teepod: Compatible for v0.3.x images

- tappd/src/main.rs
This fixes the error in the CVM console log:
```
tappd[643]: 2025-03-19T07:31:23.259508Z ERROR tappd: Health check request failed
```
> tappd: Don't reuse connections in healthy check client

- vmm/src/app.rs
- vmm/src/config.rs
- vmm/src/main.rs
- vmm/vmm.toml
When a CVM terminates unexpectedly, the dstack-vmm doesn't initiate a restart.
This PR enables the vmm to monitor terminated VMs at configured intervals and automatically restart them.
> vmm: Auto restart exited VMs

- guest-agent/rpc/proto/agent_rpc.proto
- guest-agent/src/rpc_service.rs
- sdk/curl/api.md
- sdk/go/dstack/client.go
- sdk/js/src/index.ts
- sdk/python/src/dstack_sdk/dstack_client.py
- tdx-attest/src/lib.rs
This API extends the given event to RTMR3 on TDX bare metal deployments.
> Add guest agent API: EmitEvent

- Cargo.lock
- Cargo.toml
- basefiles/tappd.service
- tappd/src/main.rs
- tappd/tappd.toml
When the app mounts tappd.sock into any container, the tappd may fail to start due to a race condition on the start order between Docker. This PR adjusts the service ordering to ensure that tappd is started before Docker.
> Fixes tappd starting order

- .github/workflows/rust.yml
- run-tests.sh
- sdk/rust/src/dstack_client.rs
> rust-sdk: Fix incorrect args in get_tls_key

- guest-agent/src/http_routes.rs
- guest-agent/src/models.rs
- guest-agent/templates/metrics.tpl
Example output:
```
system_os_name{os_name="Ubuntu"} 1
system_os_version{os_version="24.04"} 1
system_kernel_version{kernel_version="6.8.0-1013-intel"} 1
system_cpu_model{cpu_model="cpu0 @800 MHz"} 1
system_num_cpus 32
system_memory_total 269773893632
system_memory_available 18791055360
system_memory_used 250982838272
system_memory_free 3640774656
system_swap_total 8589930496
system_swap_used 8589090816
system_swap_free 839680
system_uptime 10035004
system_load_average_1m 660
system_load_average_5m 643
system_load_average_15m 691
disk_total_size{name="/dev/mapper/ubuntu--vg-ubuntu--lv", mount_point="/"} 210779168768
disk_free_size{name="/dev/mapper/ubuntu--vg-ubuntu--lv", mount_point="/"} 54533517312
disk_used_size{name="/dev/mapper/ubuntu--vg-ubuntu--lv", mount_point="/"} 156245651456 …
```
> guest-agent: Add prometheus metrics API

- sdk/js/README.md
- sdk/js/package.json
- sdk/js/src/__tests__/index.test.ts
- sdk/js/src/index.ts
- sdk/js/src/solana.ts
- sdk/js/src/viem.ts
- sdk/python/pyproject.toml
- sdk/python/src/dstack_sdk/ethereum.py
- sdk/python/src/dstack_sdk/solana.py
- sdk/python/src/dstack_sdk/tappd_client.py
- sdk/python/tests/test_ethereum.py
- sdk/python/tests/test_solana.py
This PR addresses a security vulnerability in key derivation functions while maintaining full backward compatibility. We introduce new secure APIs and restore the original behavior of existing APIs with deprecation warnings.
- **Restored original behavior** for existing APIs (`toKeypair`, `toViemAccount`, `to_keypair`, `to_account`)
- Now use first 32 bytes of key material directly (same as before)
- Added deprecation warnings to console/logs
- **Added new secure APIs** (`toKeypairSecure`, `toViemAccountSecure`, `to_keypair_secure`, `to_account_secure`)
- Use SHA256 hash of complete key material for enhanced security
- Follow cryptographic best practices
- **JavaScript**: `@phala/dstack-sdk@0.2.1`
- **Python**: `dstack-sdk@0.2.1`
- **Original APIs**: Use first 32 bytes directly (restored …
> Add secure key derivation APIs and restore backward compatibility

- tproxy/rpc/proto/tproxy_rpc.proto
- tproxy/src/admin_service.rs
- tproxy/src/main_service.rs
The `get_meta` API is proposed for heartbeat in the admin API. When we move `list` and `get_info` APIs to separate admin RPC, we'll need to move this API as well.
This PR is proposed for the dstack v0.3.x branch.
> fix(gateway): move get_meta to admin API for v0.3.x

- vmm/src/vmm-cli.py
When deploying KMS without the `key_provider_id`, dstack-utils returns an error:
```
dstack-prepare.sh[412]: 2025-06-23T15:13:32.575049Z  INFO cmd_lib::builtins: Mounting host-shared
dstack-prepare.sh[412]: 2025-06-23T15:13:32.589631Z  INFO cmd_lib::builtins: Copying host-shared files
dstack-prepare.sh[412]: 2025-06-23T15:13:32.601762Z  INFO cmd_lib::builtins: Unmounting host-shared
dstack-prepare.sh[412]: Error: Failed to parse json
dstack-prepare.sh[412]: Caused by:
dstack-prepare.sh[412]:     invalid type: null, expected a string at line 9 column 27
[FAILED] Failed to start DStack Guest Preparation Service.
```
Fixed it by setting `key_provider_id` to an empty string when it's `None` in vmm-cli.py
> fix(vmm-cli): unmatched app_compose when no key provider id.

- sdk/curl/api-tappd.md
- sdk/curl/api.md
- sdk/go/dstack/client.go
- sdk/go/tappd/client.go
- sdk/js/src/index.ts
- sdk/python/src/dstack_sdk/dstack_client.py
- sdk/rust/src/dstack_client.rs
- sdk/rust/tests/test_client.rs
These fields no longer exists in the latest API so remove it.
> sdk: Remove more fields in AppInfo

- sdk/js/package.json
- sdk/js/src/__tests__/index.test.ts
- sdk/js/src/__tests__/solana.test.ts
- sdk/js/src/__tests__/viem.test.ts
- sdk/js/src/index.ts
- sdk/js/src/solana.ts
- sdk/js/src/viem.ts
This PR adds backward compatibility with the refreshed TappdClient implementation by accessing the old tappd.sock in the JS SDK. It also ensures smooth migration from v0.1.x and v0.2.x of the JS SDK.
To use the compatible APIs, the app needs to mount both `/var/run/tappd.sock` and `/var/run/dstack.sock` into the container simultaneously.
Example docker-compose file:
```yaml
services:
jupyter:
image: quay.io/jupyter/base-notebook
volumes:
- /var/run/tappd.sock:/var/run/tappd.sock
- /var/run/dstack.sock:/var/run/dstack.sock
```
JS usage:
```js
const client = new TappdClient();
const key = await client.deriveKey("key/path");
const privateKey = await webcrypto.subtle.importKey(
"pkcs8",
key.asUint8Array(),
{
name: "ECDH",
namedCurve: "P-256"
},
true,
["deriveKey"]
);
```
> jssdk: Add back TappdClient for compatibility

- .github/workflows/sdk.yaml
- Cargo.lock
- run-tests.sh
- sdk/run-tests.sh
- sdk/rust/Cargo.toml
- sdk/rust/README.md
- sdk/rust/examples/dstack_client_usage.rs
- sdk/rust/examples/tappd_client_usage.rs
- sdk/rust/src/lib.rs
- sdk/rust/src/tappd_client.rs
- sdk/rust/tests/test_tappd_client.rs
The compatible API resides in `TappdClient`, maintaining consistency with the js-sdk.
> rust-sdk: Add support for legacy TappdClient

- certbot/cli/src/main.rs
Hi! I'm Tei from Sunnyside Labs.
This PR enables certbot CLI to manage TLS cert of multi domain names.
This change is a breaking change, and will break the existing cerbot configs.
> Make certbot cli support multi domains

- kms/dstack-app/compose-dev.yaml
- kms/dstack-app/deploy-to-vmm.sh
- kms/dstack-app/entrypoint.sh
Hi! I'm Tei from Sunnyside Labs.
This PR adds configuration options for running KMS using docker compose and run script.
- `VERIFY_IMAGE`: Allow disabling image hash verification feature to use custom dstack OS image.
- `GIT_REPOSITORY`: Allow to compile and run KMS from forked repository.
I had to disable `verify` option to run my custom dstack OS image. And to apply & test this change, I needed to specify my forked repository in the docker compose file.
This change is backward compatible and does not affect existing behavior unless configured explicitly.
> Make KMS configurable

- gateway/gateway.toml
- gateway/rpc/proto/gateway_rpc.proto
- gateway/src/config.rs
- gateway/src/main_service.rs
- gateway/src/proxy/tls_passthough.rs
This PR adds optional support for `TXT` prefix `_tapp-address`, which is compatible with dstack 0.3.x.
> gw: Add 0.3.x compatibility custom domain dns prefix

- docs/dstack-gateway.md
- gateway/src/main_service.rs
- gateway/src/proxy.rs
- gateway/src/proxy/tls_terminate.rs
This PR adds a new prefix `g` to the port part which means the backend is serving on HTTP/2.
The gateway supports the following URL format:
- `<app_id>[-<port>][<suffix>].<base_domain>`
Where:
- `<app_id>`: The application identifier
- `<port>`: Optional port number (defaults to 80 for HTTP, 443 for HTTPS)
- `<suffix>`: Optional suffix flags:
- `s`: Enable TLS passthrough (proxy passes encrypted traffic directly to backend)
- `g`: Enable HTTP/2 (gRPC) support (proxy advertises h2 via ALPN)
Examples:
- `<app_id>.gateway.example.com` - Default HTTP on port 80
- `<app_id>-8080.gateway.example.com` - HTTP on port 8080
- `<app_id>-s.gateway.example.com` - TLS passthrough on port 443
- `<app_id>-443s.gateway.example.com` - TLS passthrough on port 443
- `<app_id>-50051g.gateway.example.com` - …
> gateway: gRPC proxy support

- Cargo.lock
- Cargo.toml
- sdk/rust/types/Cargo.toml
- sdk/rust/types/src/dstack.rs
- sdk/rust/types/src/tappd.rs
This PR adds optional [Borsh](https://borsh.io/) (Binary Object Representation Serializer for Hashing) serialization support to the Rust SDK types, complementing the existing Serde serialization capabilities.
Borsh is a highly efficient serializer and commonly used for smart contract development.
> feat(rust-sdk): implement `borsh` serialization for rust sdk types

- sdk/python/src/dstack_sdk/dstack_client.py
- sdk/python/tests/test_client.py
With the idea borrowed from pink, which driving async function using sync net transport, we did in phat contract.
> sdk/python: Try reuse code between sync and async clients.

- README.md
Updates README documentation with details on non-kms application connectivity to agent dashboards and services, featuring gRPC access protocols via the zt-https proxy gateway.
> rdme: Update access for non-kms apps

- Cargo.lock
- Cargo.toml
`alloy` version must be bumped to >= 1.0.32 in order to compile `dstack-sdk` with recent serde version.
See tracking issue that caused this regression:
https://github.com/alloy-rs/alloy/issues/2876
> fix: dstack-sdk fails build due to alloy

- dstack-mr/src/acpi.rs
- dstack-mr/src/machine.rs
- dstack-mr/src/tdvf.rs
- dstack-types/src/lib.rs
- kms/src/main_service.rs
- vmm/src/app.rs
- vmm/src/config.rs
- vmm/src/one_shot.rs
- vmm/vmm.toml
Enabling dstack-mr to generate version-specific ACPI tables for QEMU.
image name is also added by the way.
> dstack-mr: Add qemu_version in VmConfig
