build.sh
mkguest/initramfs/config/scripts/kmfs
teepod/rpc/proto/teepod_rpc.proto
teepod/src/app.rs
teepod/src/console.html
teepod/src/main_service.rs
teepod/src/vm.rs

This PR adds a dadicated manifest file for app: `app-compose.json`. It's currently hide behind implmentation details, no user interface changed, except that the `app_id` will be the hash of this file.

Define App compose file instead of using bare docker-compose.yaml

---

Cargo.lock
kms/src/main_service.rs
ra-rpc/src/rocket_helper.rs
ra-tls/Cargo.toml
ra-tls/src/attestation.rs
ra-tls/src/cert.rs
ra-tls/src/oids.rs
tdxctl/src/main.rs
teepod/src/console.html

This PR defines content types for the tdx quote report data used in CVMs.

Define content types for quote report data

---

Cargo.lock
teepod/Cargo.toml
teepod/src/console.html
teepod/src/vm.rs
teepod/src/web_routes.rs

This PRs replace linemux with tailf as linemux is buggy and has some performance issue.

Replace linemux with tailf

---

tproxy/src/config.rs
tproxy/src/main_service.rs
tproxy/src/models.rs
tproxy/tproxy.toml

This PR let tproxy remove stale workers which get offline too long.

tproxy: Recycle stale instances

---

Cargo.lock
tproxy/Cargo.toml
tproxy/rpc/proto/tproxy_rpc.proto
tproxy/src/config.rs
tproxy/src/main_service.rs
tproxy/templates/cvmlist.html
tproxy/tproxy.toml

So that it continues serving registered workers after restart.

tproxy: persistent state

---

Cargo.lock
tproxy/Cargo.toml
tproxy/src/main_service.rs

Implements simple load balancing for tproxy (randomly selects an instance) when accessed through app_id.

tproxy: Load balance

---

tproxy/src/main_service.rs
tproxy/templates/cvmlist.html

And reject for registering without wg pubkey

tproxy: Don't allocate new ip for restarted instances

---

sdk/python/tests/test_client.py

We recently updated `tdx_quote`, and this PR proposes adding a code example as a test case for `reportdata` verification.

add test case for reportdata check

---

Cargo.lock
Cargo.toml
certbot/Cargo.toml
certbot/src/acme_client.rs
teepod/Cargo.toml
teepod/src/app/image.rs
teepod/src/config.rs
teepod/src/main.rs

This get rid of error if the path does not exists.

teepod: Use path-absolutize instead of canonicalize

---

teepod/src/app.rs
teepod/src/app/qemu.rs

This allow to login into dev images via the serial port. For debugging usage.

teepod: Open a pty for vm console

---

README.md

Add documentation for apparmor_restrict_unprivileged_userns related error.

Add apparmor_restrict_unprivileged_userns troubleshooting section

---

Cargo.lock
Cargo.toml
basefiles/app-compose.sh
tdxctl/Cargo.toml
tdxctl/src/main.rs

To get rid of the error:
```
app-compose.sh[658]: Error response from daemon: failed to create task for container: failed to start shim: start failed: : fork/exec /usr/bin/containerd-shim-runc-v2: permission denied: unknown
```

Implement tdxctl remove-orphans

---

README.md

README: Add RAM and disk requirement

---

basefiles/app-compose.service
dstack-types/src/lib.rs
dstack-types/src/shared_filenames.rs
ra-rpc/src/lib.rs
tappd/src/guest_api_service.rs
tappd/tappd.toml
tdxctl/src/fde_setup.rs
tdxctl/src/fde_setup/env_process.rs
tdxctl/src/host_api.rs
tdxctl/src/tboot.rs
tdxctl/src/utils.rs
teepod/rpc/proto/teepod_rpc.proto
teepod/src/app.rs
teepod/src/app/qemu.rs
teepod/src/console.html
teepod/src/main_service.rs
tproxy/src/config.rs
tproxy/src/main_service/snapshots/tproxy__main_service__tests__config-2.snap
tproxy/src/main_service/snapshots/tproxy__main_service__tests__config.snap
tproxy/src/main_service/tests.rs
tproxy/tapp/tproxy-entrypoint.sh

1. Only copy neccesary files
2. Store them to /tapp/.host-shared

cvm: Refactor host shared files

---

kms/rpc/proto/kms_rpc.proto
kms/src/crypto.rs
kms/src/main_service.rs
teepod/rpc/proto/teepod_rpc.proto
teepod/src/main_service.rs

kms: Sign env encrypt pubkey

---

Cargo.lock
Cargo.toml
lspci/Cargo.toml
lspci/src/lib.rs
lspci/src/snapshots/lspci__lspci.snap
teepod/Cargo.toml
teepod/rpc/proto/teepod_rpc.proto
teepod/src/app.rs
teepod/src/app/qemu.rs
teepod/src/config.rs
teepod/src/console.html
teepod/src/guest_api_service.rs
teepod/src/main_service.rs
teepod/src/teepod-cli.py
teepod/teepod.toml

This PR enables teepod to optionally connect GPU devices to CVMs during deployment

teepod: Support for GPU device integration with CVM

---

teepod/rpc/proto/teepod_rpc.proto
teepod/src/app.rs
teepod/src/console.html
teepod/src/main_service.rs

This PR Enhances the Teepod UI:
- Port mapping update
- Search capability
- Paginated display
- Efficient VM list loading

teepod: Optimize UI

---

.gitignore
Cargo.lock
gateway/Cargo.toml
gateway/dstack-app/.gitignore
gateway/dstack-app/deploy-to-vmm.sh
gateway/gateway.toml
gateway/src/config.rs
gateway/src/main_service.rs
gateway/src/main_service/auth_client.rs
vmm/src/vmm-cli.py
vmm/venv.sh

Two commits:
- The gateway support for call a external API to ask if a App CVM is allowed to login.
- The gateway app itself requires a LAUNCH_TOKEN in sercret env to run. (This might be valuable a common pattern the dstack-examples)

gw: Add authority to run

---

README.md

This makes it more friendly for newcomers

Update build steps in README

---

supervisor/src/process.rs

A supervisor.log file grew unexpectedly large due to improper tracing span implementation in async context. The entered span's crossing of the yield point led to span confusion in async tasks, resulting in tons of spans being squashed into single log entries.
```rust
let span = tracing::info_span!("process", id = process_uuid);
let _enter = span.enter();
let (killed, result) = wait_on_process(process, kill_rx).await; // The entered span crossed this yield point.
```
This PR fixes it.

supervisor: Fix bug in log span

---

sdk/rust/src/dstack_client.rs

Adds docstrings to the struct fields in the rust sdk

chore(sdk,rust): adds docstrings

---

gateway/gateway.toml
gateway/src/config.rs
gateway/src/proxy.rs
gateway/src/proxy/tls_terminate.rs

gw: Configurable TLS version and crypto provider

---

vmm/rpc/proto/vmm_rpc.proto
vmm/src/app.rs
vmm/src/config.rs
vmm/src/console.html
vmm/src/main_service.rs
vmm/vmm.toml

Confg in vmm.toml:
```
[cvm.gpu]
allow_attach_all = true
```

vmm: Add option to disable attaching all gpus

---

basefiles/dstack-prepare.sh

So that the passwd command works

cvm: Mount passwd files to data disk

---

gateway/src/main_service.rs

This bug cause the gateway allocates reserved ips to CVM.

gw: Fix reserved ip allocation

---

tproxy/rpc/proto/tproxy_rpc.proto
tproxy/src/config.rs
tproxy/src/main_service.rs
tproxy/tproxy.toml

Backport of https://github.com/Dstack-TEE/dstack/pull/245

[backport] Add RPC for gateway info

---

vmm/src/console.html

This PR adds support for updating disk size and user_config for non-kms VMs.

vmm: Allow updating non-kms VMs

---

dstack-util/src/main.rs
dstack-util/src/system_setup.rs
ra-tls/src/attestation.rs
tdx-attest/src/linux.rs

cvm: Better error report for tdx quote error

---

kms/src/main_service.rs
kms/src/onboard_service.rs

Part of fccd83de272ced9a8d5a4b9cead2d8ce8e9e7764

Revert the cert subject changes

---

basefiles/wg-checker.service
basefiles/wg-checker.sh
dstack-util/src/main.rs
dstack-util/src/system_setup.rs
guest-agent/src/guest_api_service.rs

This PR adds auto reconnect dstack-gateway to the cvm when all wg interfaces got staled.

cvm: Auto reconnect when wg get stucked

---

Cargo.lock
Cargo.toml
dstack-mr/cli/Cargo.toml
dstack-mr/cli/src/main.rs
size-parser/Cargo.toml
size-parser/README.md
size-parser/src/lib.rs

Extract the size parser function to a crate for code reuse.

Create crate size-parser

---

vmm/src/app.rs
vmm/src/config.rs
vmm/src/one_shot.rs

Dedup the code and drop 0.3.x images support by the way.

vmm: Refactor sys-config generation code
